### PR TITLE
Bump go version to 1.16

### PR DESCRIPTION
**Pull request by rail**
Let's switch to the latest and best version in order to pickup all the
improvements.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/backboard/4)

### CODE REVIEW

**Comment by rail** [comment]
There is no rush with this one.

**Comment by kenliu-crl** [comment]
LGTM

**Review by kenliu — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/backboard/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jlinder)

**Review by kenliu-crl — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/backboard/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jlinder)

**Pull request merged**
